<?php
    echo '<!DOCTYPE html>';
    echo '<html lang="pt">';
    echo '<head> <!-- Cabeçalho -->';
    echo '<title>AFD - Trabalho</title>';
    echo '<meta charset="utf-8">';
    echo '<meta name="viewport" content="width=device-width, initial-scale=1">';
    echo '<link href="arquivos/css/bootstrap.css" rel="stylesheet" type="text/css"/>';
    echo '<script src="arquivos/js/bootstrap.min.js" type="text/javascript"></script>';
    echo '<script src="arquivos/js/jquery.min.js" type="text/javascript"></script>';
    echo '<script src="arquivos/js/popper.min.js" type="text/javascript"></script>';
    echo '<link href="arquivos/css/index.css" rel="stylesheet" type="text/css"/>';
    echo '</head>';
    echo '<body>';
    echo '<nav class="navbar navbar-expand-sm bg-dark navbar-dark">';
    echo '<!-- Brand/logo -->';
    echo '<a class="navbar-brand" href="descricao.php" target="iframe">';
    echo '<img src="arquivos/img/UEM-LFA.png"  alt="logo" style="width:90px;"/>';
    echo '</a>';
    echo '<ul class="navbar-nav">';
    echo '<li class="nav-item">';
    echo '<a class="nav-link" href="inserir.php"  target="iframe">';
    echo '<button type="button" class="btn btn-primary">Inserir Descrição Formal</button>';
    echo '</a>';
    echo '</li>';
    echo '</ul>';
    echo '</nav>';
    echo '<div class="container-fluid text-center">';
    echo '<div class="row content">';
    echo '<div class="col-sm-0 sidenav">';
    echo '</div>';
    echo '<div class="col-sm-10 text-left">';
    echo '<div class="embed-responsive embed-responsive-4by3">';
    echo '<iframe class="embed-responsive iframe"  src="descricao.php"  name="iframe"></iframe>';
    echo '</div>';
    echo '</div>';
    echo '<div class="col-sm-2 sidenav">';
    echo '<img  id="myImg" src="arquivos/img/maquinas-e-linguagens-300x236.gif" alt="Máquinas"  style="width:100%;max-width:200px"/>';
    echo '</br></br></br></br></br></br></br></br>';
    echo '<img id="myImg2" alt="difícil entender..." src="arquivos/img/site.jpg"  style="width:100%;max-width:200px"/>';
    echo '</div>';
    echo '</div>';
    echo '</div>';
    echo '<!-- The Modal -->';
    echo '<div id="myModal" class="modal">';
    echo '<span class="close">&times;</span>';
    echo '<img class="modal-content" id="img01">';
    echo '<div id="caption"></div>';
    echo '</div>';
    echo '<footer class="container text-center">';
    echo '"O povo nem sabe que não sabe" - <i>Noam Chomsky.<i/>';
    echo '</footer>';
    echo '</body>';
    echo '</html>';
    echo '<script src="arquivos/js/index.js" type="text/javascript"></script>';